name = "fqnovel-api"
main = "build/worker/shim.mjs"
compatibility_date = "2024-09-06"


[vars]
install_id = "2135723325796380"
server_device_id = "4176390725582284"
aid = "1967"
update_version_code = "62532"

[build]
command = "cargo install -q worker-build && worker-build --release"